import Head from "next/head";
import styles from "../styles/Home.module.css";
import Auth from "../pages/Auth";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Social Net</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full	flex flex-col	items-center bg-brand-primary">
        <Auth />
      </main>
    </div>
  );
}
